# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Perform Unit Tests and build IPA"
  
  lane :test do
    # add actions here: https://docs.fastlane.tools/actions
# 	run_tests(devices: ["iPhone XR"],
#     		  	  scheme: "JenkinsWithFastline")
	scan(scheme: "JenkinsWithFastline")
    end
    
   lane :generate_ipa_develop do
    build_ios_app(
      configuration: "Release",
      scheme: "JenkinsWithFastline",
      clean: true,
      export_method: 'enterprise',
      output_directory: "~/Desktop/jenkins_with_fastlane/ipa", # Destination directory. Defaults to current directory.
      output_name: "fastlane_jenkins.ipa",
      include_bitcode: false,
      sdk: "iOS 12.1",
      clean: true,
      silent: true
    )
    end
    		  	  
end
